export enum RecommendationStatus {
  SUGGESTED = 'SUGGESTED',
  SCHEDULED = 'SCHEDULED',
  FAILED = 'FAILED',
  COMPLETED = 'COMPLETED',
  REJECTED = 'REJECTED',
  IN_PROGRESS = 'IN_PROGRESS',
  MANUAL_APPROVAL = 'MANUAL_APPROVAL',
  NO_LONGER_APPLICABLE = 'NO_LONGER_APPLICABLE',
  RESOURCE_DELETED = 'RESOURCE_DELETED',
  RESOURCE_FIXED = 'RESOURCE_FIXED',
  MANUALLY_FIXED = 'MANUALLY_FIXED',
}
