apiVersion: v1
kind: ConfigMap
metadata:
  name: redis-configmap
  namespace: {{ .Values.environment }}
  labels:
    app: redis
    environment: {{ .Values.environment }}
data:
  REDIS_PORT: "6379"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis
  namespace: {{ .Values.environment }}
  labels:
    app: redis
    environment: {{ .Values.environment }}
spec:
  replicas: {{ .Values.redis.replicas }}
  selector:
    matchLabels:
      app: redis
  template:
    metadata:
      labels:
        app: redis
        environment: {{ .Values.environment }}
    spec:
      containers:
        - name: redis
          image: {{ .Values.redis.image }}
          ports:
            - containerPort: 6379
          env:
            - name: REDIS_PORT
              valueFrom:
                configMapKeyRef:
                  name: redis-configmap
                  key: REDIS_PORT
---
apiVersion: v1
kind: Service
metadata:
  name: redis
  namespace: {{ .Values.environment }}
  labels:
    app: redis
spec:
  ports:
    - port: 6379
      targetPort: 6379
      protocol: TCP
      name: tcp-redis
  selector:
    app: redis