apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.analytics.name }}
  labels:
    app: {{ .Values.analytics.name }}
spec:
  replicas: {{ .Values.analytics.replicas }}
  selector:
    matchLabels:
      app: {{ .Values.analytics.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.analytics.name }}
    spec:
      containers:
      - name: {{ .Values.analytics.name }}
        image: "{{ .Values.image.repository }}/{{ .Values.analytics.image }}:{{ .Values.analytics.tag }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        env:
          {{- range $k, $v := .Values.analytics.env }}
          - name: {{ $k }}
            value: {{ tpl (tpl $v $) $ | quote }}
          {{- end }}
        ports:
        - containerPort: 8088
        resources:
          requests:
            memory: "1Gi"
            cpu: "500m"
          limits:
            memory: "2Gi"
            cpu: "1000m"
        livenessProbe:
          httpGet:
            path: /health
            port: 8088
          initialDelaySeconds: 60
          periodSeconds: 20
          timeoutSeconds: 8
          failureThreshold: 10
        readinessProbe:
          httpGet:
            path: /health
            port: 8088
          initialDelaySeconds: 30
          periodSeconds: 20
          timeoutSeconds: 8
          failureThreshold: 10
