apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.app.name }}
  labels:
    app: {{ .Values.app.name }}
spec:
  replicas: {{ .Values.app.replicas }}
  selector:
    matchLabels:
      app: {{ .Values.app.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.app.name }}
    spec:
      containers:
        - name: {{ .Values.app.name }}
          image: "{{ .Values.image.repository }}/{{ .Values.app.image }}:{{ .Values.global.version }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            - name: NODE_OPTIONS
              value: "--no-node-snapshot"
            - name: OPS_COMPONENT
              value: app
            {{- range $k, $v := .Values.openopsEnv }}
            - name: {{ $k }}
              value: {{ tpl (tpl $v $) $ | quote }}
            {{- end }}
          ports:
            - containerPort: 80
          resources:
            requests:
              memory: "1Gi"
              cpu: "500m"
            limits:
              memory: "2Gi"
              cpu: "1000m"
          readinessProbe:
            httpGet:
              path: /api/v1/health
              port: 80
            initialDelaySeconds: 30
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /api/v1/health
              port: 80
            initialDelaySeconds: 60
            periodSeconds: 30
