apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.engine.name }}
  labels:
    app: {{ .Values.engine.name }}
spec:
  replicas: {{ .Values.engine.replicas }}
  selector:
    matchLabels:
      app: {{ .Values.engine.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.engine.name }}
    spec:
      containers:
      - name: {{ .Values.engine.name }}
        image: {{ .Values.image.repository }}/{{ .Values.engine.image }}:{{ .Values.global.version }}
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        command: ["/bin/sh", "-c", "cp -r /var/tmp-base/. /tmp/ && node main.js"]
        env:
        - name: NODE_OPTIONS
          value: "--no-node-snapshot"
        - name: OPS_BASE_CODE_DIRECTORY
          value: "{{ .Values.engine.env.baseCodeDirectory }}"
        - name: OPS_COMPONENT
          value: "{{ .Values.engine.env.component }}"
        - name: OPS_SERVER_API_URL
          value: "{{ .Values.engine.env.serverApiUrl | default (printf "%s/api/" (include "openops.appServiceUrl" .)) }}"
        - name: OPS_CACHE_PATH
          value: "{{ .Values.engine.env.cachePath }}"
        - name: OPS_CONFIG_PATH
          value: "{{ .Values.engine.env.configPath }}"
        - name: OPS_ENVIRONMENT
          value: "{{ .Values.engine.env.environment }}"
        - name: OPS_ENVIRONMENT_NAME
          value: "{{ .Values.engine.env.environmentName }}"
        - name: OPS_FRONTEND_URL
          value: "{{ .Values.engine.env.frontendUrl }}"
        - name: OPS_PUBLIC_URL
          value: "{{ .Values.engine.env.publicUrl }}"
        - name: OPS_TRIGGER_DEFAULT_POLL_INTERVAL
          value: "{{ .Values.engine.env.triggerDefaultPollInterval }}"
        - name: OPS_WEBHOOK_TIMEOUT_SECONDS
          value: "{{ .Values.engine.env.webhookTimeoutSeconds }}"
        - name: OPS_BLOCKS_SOURCE
          value: "{{ .Values.engine.env.blocksSource }}"
        - name: OPS_BLOCKS_SYNC_MODE
          value: "{{ .Values.engine.env.blocksSyncMode }}"
        - name: OPS_ENABLE_HOST_SESSION
          value: "{{ .Values.engine.env.enableHostSession }}"
        - name: OPS_EXEC_FILE_MAX_BUFFER_SIZE_MB
          value: "{{ .Values.engine.env.execFileMaxBufferSizeMb }}"
        - name: OPS_QUEUE_MODE
          value: "{{ .Values.engine.env.queueMode }}"
        - name: OPS_REDIS_HOST
          value: "{{ include "openops.redisHost" . }}"
        - name: OPS_REDIS_PORT
          value: "{{ include "openops.redisPort" . }}"
        - name: OPS_DB_TYPE
          value: "{{ .Values.engine.env.dbType }}"
        - name: OPS_SLACK_ENABLE_INTERACTIONS
          value: "{{ .Values.engine.env.slackEnableInteractions }}"
        - name: OPS_ENGINE_URL
          value: "{{ .Values.engine.env.engineUrl | default (printf "%s/execute" (include "openops.engineServiceUrl" .)) }}"
        - name: OPS_EXECUTION_MODE
          value: "{{ .Values.engine.env.executionMode }}"
        - name: OPS_LOG_LEVEL
          value: "{{ .Values.engine.env.logLevel }}"
        - name: OPS_LOG_PRETTY
          value: "{{ .Values.engine.env.logPretty }}"
        - name: OPS_TELEMETRY_COLLECTOR_URL
          value: "{{ .Values.engine.env.telemetryCollectorUrl }}"
        - name: OPS_DARK_THEME_ENABLED
          value: "{{ .Values.engine.env.darkThemeEnabled }}"
        - name: OPS_CODE_BLOCK_MEMORY_LIMIT_IN_MB
          value: "{{ .Values.engine.env.codeBlockMemoryLimitInMb }}"
        - name: OPS_AWS_ENABLE_IMPLICIT_ROLE
          value: "{{ .Values.engine.env.awsEnableImplicitRole }}"
        - name: HOST_AZURE_CONFIG_DIR
          value: "{{ .Values.engine.env.hostAzureConfigDir }}"
        - name: HOST_CLOUDSDK_CONFIG
          value: "{{ .Values.engine.env.hostCloudsdkConfig }}"
        ports:
        - containerPort: 3005
        resources:
          requests:
            memory: "512Mi"
            cpu: "250m"
          limits:
            memory: "1Gi"
            cpu: "500m"
        envFrom:
        - secretRef:
            name: openops-secrets
        volumeMounts:
        - name: azure-config
          mountPath: /tmp/azure
        - name: gcloud-config
          mountPath: /tmp/gcloud
      volumes:
      - name: azure-config
        persistentVolumeClaim:
          claimName: azure-config-pvc
      - name: gcloud-config
        persistentVolumeClaim:
          claimName: gcloud-config-pvc