apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.tables.name }}
  labels:
    app: {{ .Values.tables.name }}
spec:
  replicas: {{ .Values.tables.replicas }}
  selector:
    matchLabels:
      app: {{ .Values.tables.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.tables.name }}
    spec:
      containers:
      - name: {{ .Values.tables.name }}
        image: "{{ .Values.image.repository }}/{{ .Values.tables.image }}:{{ .Values.tables.tag }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        env:
          {{- range $k, $v := .Values.tables.env }}
          - name: {{ $k }}
            value: {{ tpl (tpl $v $) $ | quote }}
          {{- end }}
        resources:
          requests:
            memory: "512Mi"
        volumeMounts:
        - name: tables-data
          mountPath: /baserow/data
        livenessProbe:
          exec:
            command:
            - /bin/sh
            - -c
            - /baserow/backend/docker/docker-entrypoint.sh backend-healthcheck
          initialDelaySeconds: 60
          periodSeconds: 20
          timeoutSeconds: 8
          failureThreshold: 10
        readinessProbe:
          exec:
            command:
            - /bin/sh
            - -c
            - /baserow/backend/docker/docker-entrypoint.sh backend-healthcheck
          initialDelaySeconds: 30
          periodSeconds: 20
          timeoutSeconds: 8
          failureThreshold: 10
      volumes:
      - name: tables-data
        persistentVolumeClaim:
          claimName: tables-data-pvc
