apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: azure-config-pvc
  labels:
    app: {{ .Values.engine.name }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi