apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: redis-data-pvc
  labels:
    app: {{ .Values.redis.name }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.redis.storage.size }}
  {{- if .Values.redis.storage.storageClass }}
  storageClassName: {{ .Values.redis.storage.storageClass }}
  {{- end }}