apiVersion: v1
kind: Secret
metadata:
  name: openops-secrets
  labels:
    app: openops
type: Opaque
data:
  encryptionKey: {{ .Values.secrets.encryptionKey | b64enc }}
  jwtSecret: {{ .Values.secrets.jwtSecret | b64enc }}
  adminEmail: {{ .Values.secrets.adminEmail | b64enc }}
  adminPassword: {{ .Values.secrets.adminPassword | b64enc }}
  analyticsAdminPassword: {{ .Values.secrets.analyticsAdminPassword | b64enc }}
  analyticsPoweruserPassword: {{ .Values.secrets.analyticsPoweruserPassword | b64enc }}
  postgresUsername: {{ .Values.secrets.postgresUsername | b64enc }}
  postgresPassword: {{ .Values.secrets.postgresPassword | b64enc }}
  postgresDatabase: {{ .Values.secrets.postgresDatabase | b64enc }}
  tablesPublicUrl: {{ .Values.secrets.tablesPublicUrl | b64enc }}
  tablesDbHost: {{ .Values.secrets.tablesDbHost | b64enc }}
  jwtTokenLifetimeHours: {{ .Values.secrets.jwtTokenLifetimeHours | b64enc }}
  tablesTokenLifetimeMinutes: {{ .Values.secrets.tablesTokenLifetimeMinutes | b64enc }}
  tablesDatabaseName: {{ .Values.secrets.tablesDatabaseName | b64enc }}
  postgresHost: {{ .Values.secrets.postgresHost | b64enc }}
  postgresPort: {{ .Values.secrets.postgresPort | b64enc }}
  apiKey: {{ .Values.secrets.apiKey | b64enc }}
  slackAppSigningSecret: {{ .Values.secrets.slackAppSigningSecret | b64enc }}
  logzioToken: {{ .Values.secrets.logzioToken | b64enc }}
  logzioMetricsToken: {{ .Values.secrets.logzioMetricsToken | b64enc }}
  chromaticProjectToken: {{ .Values.secrets.chromaticProjectToken | b64enc }}