apiVersion: v1
kind: Secret
metadata:
  name: openops-secrets
  labels:
    app: openops
type: Opaque
data:
  encryptionKey: {{ .Values.secrets.encryptionKey | default "abcdef123456789abcdef123456789ab" | b64enc }}
  jwtSecret: {{ .Values.secrets.jwtSecret | default "please-change-this-secret" | b64enc }}
  adminEmail: {{ .Values.secrets.adminEmail | default "admin@openops.com" | b64enc }}
  adminPassword: {{ .Values.secrets.adminPassword | default "please-change-this-password-1" | b64enc }}
  analyticsAdminPassword: {{ .Values.secrets.analyticsAdminPassword | default "please-change-this-password-1" | b64enc }}
  analyticsPoweruserPassword: {{ .Values.secrets.analyticsPoweruserPassword | default "please-change-this-password-1" | b64enc }}
  postgresUsername: {{ .Values.secrets.postgresUsername | default "postgres" | b64enc }}
  postgresPassword: {{ .Values.secrets.postgresPassword | default "please-change-this-password-1" | b64enc }}
  postgresDatabase: {{ .Values.secrets.postgresDatabase | default "openops" | b64enc }}
  tablesPublicUrl: {{ .Values.secrets.tablesPublicUrl | default "http://localhost" | b64enc }}
  tablesDbHost: {{ .Values.secrets.tablesDbHost | default .Values.postgres.name | b64enc }}
  jwtTokenLifetimeHours: {{ .Values.secrets.jwtTokenLifetimeHours | b64enc }}
  tablesTokenLifetimeMinutes: {{ .Values.secrets.tablesTokenLifetimeMinutes | b64enc }}
  tablesDatabaseName: {{ .Values.secrets.tablesDatabaseName | default "tables" | b64enc }}
  postgresHost: {{ .Values.secrets.postgresHost | default .Values.postgres.name | b64enc }}
  postgresPort: {{ .Values.secrets.postgresPort | default (.Values.postgres.service.port | toString) | b64enc }}
  apiKey: {{ .Values.secrets.apiKey | default "api-key" | b64enc }}
  slackAppSigningSecret: {{ .Values.secrets.slackAppSigningSecret | b64enc }}
