apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.postgres.name }}
  labels:
    app: {{ .Values.postgres.name }}
spec:
  type: ClusterIP
  ports:
  - port: {{ .Values.postgres.service.port }}
    targetPort: 5432
    protocol: TCP
    name: postgres
  selector:
    app: {{ .Values.postgres.name }}