apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.engine.name }}
  labels:
    app: {{ .Values.engine.name }}
spec:
  type: ClusterIP
  ports:
  - port: 3005
    targetPort: 3005
    protocol: TCP
    name: http
  selector:
    app: {{ .Values.engine.name }}