apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.tables.name }}
  labels:
    app: {{ .Values.tables.name }}
spec:
  type: ClusterIP
  ports:
  - port: 80
    targetPort: 80
    protocol: TCP
    name: http
  selector:
    app: {{ .Values.tables.name }}