blank_issues_enabled: false
contact_links:
  - name: Slack Community
    url: https://slack.openops.com
    about: Join our slack community for support, discussions and product feedback.
  - name: Documentation
    url: https://docs.openops.com
    about: Check out our docs to see if there's already a solution to your issue.
