# .github/workflows/chromatic.yml

name: "Chromatic"

on: push

jobs:
  chromatic:
    runs-on: ubuntu-latest
    env:
      CHROMATIC_PROJECT_TOKEN: ${{ secrets.CHROMATIC_PROJECT_TOKEN }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Cache node_modules
        id: node-modules-cache
        uses: actions/cache@v4
        with:
          path: node_modules
          key: node-modules-cache-${{ hashFiles('package-lock.json', '.npmrc') }}
          save-always: true

      - name: Install dependencies
        if: steps.node-modules-cache.outputs.cache-hit != 'true'
        run: npm ci --prefer-offline

      - name: Run Chromatic
        # ¯\_(ツ)_/¯ TODO: use chromaui/action@latest(or fixed > v11.16.5) version when SB comes with a final stable fix: https://github.com/chromaui/chromatic-cli/pull/1049.
        # Also remove the build-storybook npm script and add buildCommand option to chromatic.config.json
        if: env.CHROMATIC_PROJECT_TOKEN
        uses: chromaui/action@v11.27.0 
        with:
          projectToken: ${{ secrets.CHROMATIC_PROJECT_TOKEN }}
          onlyChanged: true # 👈 Required option to enable TurboSnap
          storybookBaseDir: ./packages/ui-components