name: 'Close stale issues and PRs'

on:
  schedule:
    - cron: '30 18 * * 1'
  workflow_dispatch:

permissions:
  actions: write
  issues: write
  pull-requests: write
  contents: read

jobs:
  stale:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/stale@v10
        with:
          days-before-pr-stale: 60
          days-before-pr-close: 5

          days-before-issue-stale: 60
          days-before-issue-close: 5

          stale-issue-label: 'stale'
          stale-issue-message: >
            This issue has been automatically marked as stale because it has not had
            activity in the last 60 days. It will be closed in 5 days if no further activity occurs. Please
            feel free to leave a comment if you believe the issue is still relevant.
            Thank you for your contributions!

          stale-pr-label: 'stale'
          stale-pr-message: >
            This pull request has been automatically marked as stale because it has not had
            activity in the last 60 days. It will be closed in 5 days if no further activity occurs. Please
            feel free to give a status update by leaving a comment. Thank you for your contributions!

          close-issue-message: >
            This issue has been automatically closed because it has not had any further
            activity in the last 5 days. Thank you for your contributions!
          close-pr-message: >
            This pull request has been automatically closed because it has not had any further
            activity in the last 5 days. Thank you for your contributions!

          debug-only: true
